CalCal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView
urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name='index.html'), name='home'),
    path('admin/', admin.site.urls),
    path('FoodInfo/', include('FoodInfo.urls')),
    path('User/', include('User.urls')),
]

FoodInfo/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'FoodInfo'

urlpatterns = [
    path('service/', views.service, name='service'),
    path('search/', views.search, name='search'),
    path('table/', views.table, name='table'),
    path('mypage/', views.mypage, name='mypage'),
    path('<int:food_id>/delete/', views.delete, name='delete'),
    path('<int:food_id>/update/', views.update, name='update'),
    path('serviceByDate/', views.serviceByDate, name='serviceByDate'),
    path('searchByDate/', views.searchByDate, name='searchByDate'),
    path('<int:food_id>/getDate/delete/', views.deleteByDate, name='deleteByDate'),
    path('<int:food_id>/getDate/update/', views.updateByDate, name='updateByDate')
]

User/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'User'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update_user/', views.update_user, name='update_user'),
]

User/models.py
from django.db import models
from django.contrib.auth.models import (BaseUserManager, AbstractBaseUser)

GENDER_CHOICES = (
    (0, 'Female'),
    (1, 'Male'),
)

class UserManager(BaseUserManager):
    def create_user(self, username,email,  age, weight, height, gender, password=None):
        if not username:
            raise ValueError('Users must have an email address')

        user = self.model(
            username=username,
            email=email,
            age=age,
            weight=weight,
            height=height,
            gender=gender,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, age, weight, height, gender, password):
        user = self.create_user(
            username,
            email=email,
            password=password,
            age=age,
            weight=weight,
            height=height,
            gender=gender,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    username = models.CharField(
        verbose_name='username',
        max_length=40,
        unique=True,
    )
    email = models.EmailField(
        verbose_name='email',
        max_length=240,
    )

    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )

    age = models.PositiveIntegerField(null=True, blank=True)
    weight = models.PositiveIntegerField(null=True, blank=True)
    height = models.PositiveIntegerField(null=True, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    # gender = models.SmallIntegerField(choices=GENDER_CHOICES)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'age', 'gender', 'weight', 'height']

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

CalCal/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>
<body>

{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

</body>
</html>

CalCal/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

CalCal/templates/index.html
<!DOCTYPE HTML>
<!--
	Spectral by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>CalCal First Project</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="/static/assets/css/main.css" />
		<noscript><link rel="stylesheet" href="/static/assets/css/noscript.css" /></noscript>

	</head>
	<body class="landing is-preload" style="background-image: url('/static/assets/images/12345.jpg');">

		<!-- Page Wrapper -->
			<div id="page-wrapper">

				<!-- Header -->
					<header id="header" class="alt">
						<h1><a href="index.html">Spectral</a></h1>
					</header>

				<!-- Banner -->
					<section id="banner">
						<div class="inner">
							<h2>CalCal</h2>
							<p>First project<br />
							Carbohydrate, Protein, Fat<br /><br /></p>
							<ul class="actions special">
								<li><a href="{% url 'User:login' %}" class="button success">Welcome</a></li>
							</ul>
						</div>
					</section>

			</div>

		<!-- Scripts -->
			<script src="/static/assets/js/jquery.min.js"></script>
			<script src="/static/assets/js/jquery.scrollex.min.js"></script>
			<script src="/static/assets/js/jquery.scrolly.min.js"></script>
			<script src="/static/assets/js/browser.min.js"></script>
			<script src="/static/assets/js/breakpoints.min.js"></script>
			<script src="/static/assets/js/util.js"></script>
			<script src="/static/assets/js/main.js"></script>

	</body>
</html>

CalCal/templates/login.html
{% extends "login_base.html" %}
{% block content %}
<div class="limiter">
    <div class="container-login100" style="background-image: url('/static/assets/images/12345.jpg');">
        <div class="wrap-login100 p-t-30 p-b-50">
            <span class="login100-form-title p-b-41">
                Account Login
            </span>
            <form method="post" class="login100-form validate-form p-b-33 p-t-5" action="{% url 'User:login' %}">
                {% csrf_token %}
                {% include "form_errors.html" %}
                <div class="wrap-input100 validate-input" data-validate = "Enter username">
                    <input class="input100" type="text" name="username" placeholder="User name"
                        id="username" value="{{ form.username.value|default_if_none:'' }}">
                    <span class="focus-input100" data-placeholder="&#xe82a;"></span>
                </div>
                <div class="wrap-input100">
                    <input type="password" class="input100" name="password" id="password"
                           placeholder="Password" value="{{ form.password.value|default_if_none:'' }}">
                    <span class="focus-input100" data-placeholder="&#xe80f;"></span>
                </div>
                <div class="container-login100-form-btn m-t-32">
                    <button type="submit" class="login100-form-btn">
                        Login
                    </button>
                </div>
                <div class="col-8 text-right">
                    <span><a href="{% url 'User:signup' %}">계정을 만드세요.</a></span>
                    <!--폰트 혹은 디자인 변경 필요-->
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

CalCal/templates/login_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <!--===============================================================================================-->
	<link rel="icon" type="image/png" href="/static/login/images/icons/favicon.ico">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/login/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/login/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/login/vendor/animate/animate.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/login/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/login/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/login/vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/login/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/login/css/util.css">
	<link rel="stylesheet" type="text/css" href="/static/login/css/main.css">
<!--===============================================================================================-->
</head>
<body>

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

	<div id="dropDownSelect1"></div>
<!--===============================================================================================-->
	<script src="/static/login/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/login/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/login/vendor/bootstrap/js/popper.js"></script>
	<script src="/static/login/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/login/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/login/vendor/daterangepicker/moment.min.js"></script>
	<script src="/static/login/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="/static/login/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="/static/login/js/main.js"></script>

</body>
</html>

CalCal/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'FoodInfo:service' %}">CalCal</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'User:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'User:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

CalCal/templates/signup.html
{% extends "login_base.html" %}
{% block content %}
<div class="limiter">
    <div class="container-login100" style="background-image: url('/static/assets/images/12345.jpg');">
        <div class="wrap-login100 p-t-30 p-b-50">
            <span class="login100-form-title p-b-41">
                Sign up
            </span>
            <form method="post" class="login100-form validate-form p-b-33 p-t-5">
                {% csrf_token %}
                {% include "form_errors.html" %}
                <div class="wrap-input100">
                    <input type="text" class="input100" name="username" id="username"
                           placeholder="User name" value="{{ form.username.value|default_if_none:'' }}">
                    <span class="focus-input100" data-placeholder="&#xe82a;"></span>

                </div>
                <div class="wrap-input100">
                    <input type="password" class="input100" name="password1" id="password1"
                           placeholder="password1"value="{{ form.password.value|default_if_none:'' }}">
                    <span class="focus-input100" data-placeholder="&#xe80f;"></span>

                </div>
                <div class="wrap-input100">
                    <input type="password" class="input100" name="password2" id="password2"
                           placeholder="password2" value="{{ form.password.value|default_if_none:'' }}">
                    <span class="focus-input100" data-placeholder="&#xe80f;"></span>
                </div>
                <div class="wrap-input100">
                    <input type="text" class="input100" name="email" id="email"
                           placeholder="email" value="{{ form.email.value|default_if_none:'' }}">
                    <span class="focus-input100" data-placeholder="&#xf16a;"></span>
                </div>
                <div class="wrap-input100">
                    <input type="number" class="input100" name="age" id="age"
                           placeholder="age" value="{{ form.age.value|default_if_none:'' }}">
                    <span class="focus-input100" data-placeholder="&#xf16a;"></span>
                </div>
                <div class="wrap-input100">
                    <input type="number" class="input100" name="weight" id="weight"
                           placeholder="weight" value="{{ form.weight.value|default_if_none:'' }}">
                    <span class="focus-input100" data-placeholder="&#xf16a;"></span>
                </div>
                <div class="wrap-input100">
                    <input type="number" class="input100" name="height" id="height"
                           placeholder="height" value="{{ form.height.value|default_if_none:'' }}">
                    <span class="focus-input100" data-placeholder="&#xf16a;"></span>
                </div>
                <div class="wrap-input100">
                    <label for="id_gender" class="input100" style="display:inline;">gender</label>&nbsp;&nbsp;&nbsp;
                    <select class="custom-select md-form" name="gender" id="id_gender" style="width: 150px;">
                        {% for choice in form.gender %}
                            {{choice}}
                        {% endfor %}
                    </select>
                </div>
                <div class="container-login100-form-btn m-t-32">
                    <button type="submit" class="login100-form-btn">생성하기</button>
                </div>
                <div class="col-8 text-right p-r-25" >
                    <span><a href="{% url 'User:login' %}">로그인 하세요</a></span>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

CalCal/templates/update.html
<!doctype html>
<html lang="en">

<head>
	<title>CalCal First project</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<!-- VENDOR CSS -->
	<link rel="stylesheet" href="/static/service/vendor/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="/static/service/vendor/font-awesome/css/font-awesome.min.css">
	<link rel="stylesheet" href="/static/service/vendor/linearicons/style.css">
	<link rel="stylesheet" href="/static/service/vendor/chartist/css/chartist-custom.css">
	<!-- MAIN CSS -->
	<link rel="stylesheet" href="/static/service/css/main.css">
	<!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
	<link rel="stylesheet" href="/static/service/css/demo.css">
	<!-- GOOGLE FONTS -->
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
	<!-- ICONS -->
	<link rel="apple-touch-icon" sizes="76x76" href="/static/service/img/apple-icon.png">
	<link rel="icon" type="image/png" sizes="96x96" href="/static/service/img/favicon.png">
	<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>


</head>
<style>
	.navbar-default .brand {
    float: left;
    padding: 15px 10px;
    background-color: #fff;
}
	input[type=number] {
	  line-height: 30px;
}

	input[type=number]::-webkit-inner-spin-button {
	  width: 30px;
	  height: 30px;
}
	#wrapper .main {
		-webkit-transition: all 0.3s ease-in-out;
		-moz-transition: all 0.3s ease-in-out;
		-ms-transition: all 0.3s ease-in-out;
		-o-transition: all 0.3s ease-in-out;
		transition: all 0.3s ease-in-out;
		width: calc(100% - 500px);
		left: 0;
		position: relative;
		float: right;
		background-color: #f5f5fa;
}
	.profile-left {
    padding-left: 0;
    float: left;
    width: 70%;
    height: 100%;
    position: absolute;
    background-color: #F8F8F8;
}
	.main-content {
    padding: 2px 10px;
}
</style>
<body>
<script>
	var kcalData = 0
	{% for todayFood in todayTable %}
		kcalData = kcalData + {{ todayFood.kcal }}
	{% endfor %}
</script>
	<!-- WRAPPER -->
	<b id="wrapper">
		<!-- NAVBAR -->
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="brand" >
<!--				<a href="service.html"><img src="/static/service/img/logo-dark.png" alt="Klorofil Logo" class="img-responsive logo"></a>-->
				    <a class="navbar-brand" href="{% url 'FoodInfo:service' %}" style="">CalCal</a>
			</div>
			<div class="container-fluid">
				<div class="navbar-btn">
					<button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
				</div>
				<form class="navbar-form navbar-left" action="{% url 'FoodInfo:search' %}" method="POST">
					  {% csrf_token %}
					<div class="input-group">
						<input type="search" value="{{ q }}" class="form-control" placeholder="Search" name="q" >
						<input type="hidden" value="{{ baseDate }}" name="baseDate"></input>
						<span class="input-group-btn">
						<button type="submit" class="btn btn-primary">Go</button></span>
					</div>
				</form>
<!--				<div class="navbar-btn navbar-btn-right">-->
<!--					<a class="btn btn-success update-pro" href="https://www.themeineed.com/downloads/klorofil-pro-bootstrap-admin-dashboard-template/?utm_source=klorofil&utm_medium=template&utm_campaign=KlorofilPro" title="Upgrade to Pro" target="_blank"><i class="fa fa-rocket"></i> <span>UPGRADE TO PRO</span></a>-->
<!--				</div>-->
				<div id="navbar-menu">
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							{% if user.is_authenticated %}
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="/static/service/img/1.PNG" class="img-circle" alt="Avatar"> <span>{{ user.username }}</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
							<ul class="dropdown-menu">
								<li><a href="{% url 'FoodInfo:mypage' %}"><i class="lnr lnr-user"></i> <span>My Profile</span></a></li>
								<li><a href="{% url 'User:logout' %}"><i class="lnr lnr-exit"></i> <span>Logout</span></a></li>
							</ul>
							{% endif %}
						</li>
					</ul>
				</div>
			</div>
		</nav>
		<!-- END NAVBAR -->
		<div id="sidebar-nav" class="sidebar">
			<div class="sidebar-scroll">
				<nav>
					<ul class="nav">
						<li><a href="{%url 'FoodInfo:service' %}" class=""><i class="lnr lnr-home"></i> <span>Service</span></a></li>
						<li><a href="{%url 'FoodInfo:table' %}" class=""><i class="lnr lnr-dice"></i> <span>Tables</span></a></li>
						<li><a href="{%url 'FoodInfo:mypage' %}" class="active"><i class="lnr lnr-file-empty"></i> <span>MyPages</span> </a></li>
					</ul>
				</nav>
			</div>
		</div>
		<!-- END LEFT SIDEBAR -->
		<!-- MAIN -->
		<div class="main">
			<!-- MAIN CONTENT -->
			<div class="main-content">
				<div class="container-fluid">
					<div class="panel panel-profile">
						<div class="clearfix">
							<!-- LEFT COLUMN -->
							<div class="profile-left">
								<!-- PROFILE HEADER -->
								<div class="profile-header">
									<div class="overlay"></div>
									<div class="profile-main">
										<img src="/static/service/img/user-medium.gif" class="img-circle" alt="Avatar">
										<h3 class="name">{{ user.username }}</h3>
										<span class="online-status status-available">Available</span>
									</div>
									<div class="profile-stat">
										<div class="row">
											<div class="col-md-4 stat-item">
												{{ user.height }} cm <span>height</span>
											</div>
											<div class="col-md-4 stat-item">
												{{ user.weight }} kg <span>weight</span>
											</div>
											<div class="col-md-4 stat-item">
												<span class="number"><script>document.write(kcalData.toFixed())</script></span>
												<span>Today kcal</span>
											</div>
										</div>
									</div>
								</div>
								<!-- END PROFILE HEADER -->

								<!-- PROFILE DETAIL -->
								<div class="profile-main">
									<div class="profile-info">
										<h4 class="heading">User Info</h4>

                                        <!-- 여기서부터 form -->
										<form action="{% url 'User:update_user' %}" method="POST" >
                                            {% csrf_token %}
                                                <div class="form-group">
                                                     <label for="id_username">Username</label>
                                                      <input type="text" name="username" value={{ user.username }} maxlength="40"
                                                          class="form-control" placeholder="Username" title="" required id="id_username" readonly>
                                                 </div>

                                                <div class="form-group">
                                                    <label for="id_email">Email</label>
                                                    <input type="email" name="email" value={{ user.email }} maxlength="240"
                                                           class="form-control" placeholder="Email" title="" required id="id_email">
                                                </div>

                                                <div class="form-group">
                                                    <label for="id_age">Age</label>
                                                    <input type="number" name="age" value={{ user.age }} maxlength="240"
                                                           class="form-control" placeholder="Age" title="" required id="id_age">
                                                </div>

                                                <div class="form-group">
                                                    <label for="id_weight">Weight</label>
                                                    <input type="number" name="weight" value={{ user.weight }} maxlength="240"
                                                           class="form-control" placeholder="Weight" title="" required id="id_weight">
                                                </div>

                                                 <div class="form-group">
                                                    <label for="id_height">Height</label>
                                                    <input type="number" name="height" value={{ user.height }} maxlength="240"
                                                           class="form-control" placeholder="Height" title="" required id="id_height">
                                                </div>

                                                 <div class="form-group">
                                                    <label for="id_gender">Gender</label>
                                                    <fieldset class="form-control">
                                                        <input type="radio" name="gender" value='M' required id="id_gender" checked>M &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                        <input type="radio" name="gender" value='F' required id="id_gender" checked>F
                                                    </fieldset>
                                                </div>
                                                <br>
                                            <div class="text-center"><input type="submit" class="btn-primary" value="수정 완료"/></div>

                                        </form>
									</div>
								<!-- END PROFILE DETAIL -->
							</div>
							<!-- END LEFT COLUMN -->

						</div>
					</div>
				</div>
			</div>
			<!-- END MAIN CONTENT -->
		</div>
	</div>
	<!-- END WRAPPER -->
	<!-- Javascript -->
	<script src="/static/service/vendor/jquery/jquery.min.js"></script>
	<script src="/static/service/vendor/bootstrap/js/bootstrap.min.js"></script>
	<script src="/static/service/vendor/jquery-slimscroll/jquery.slimscroll.min.js"></script>
	<script src="/static/service/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>
	<script src="/static/service/vendor/chartist/js/chartist.min.js"></script>
	<script src="/static/service/scripts/klorofil-common.js"></script>
	</b>
</body>

</html>